//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WonderlandEntities : DbContext
    {
        public WonderlandEntities()
            : base("name=WonderlandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<WL_CHECK_DATES> WL_CHECK_DATES { get; set; }
        public DbSet<WL_LIST_GUARD> WL_LIST_GUARD { get; set; }
        public DbSet<WL_LIST_GUARD_SETTINGS> WL_LIST_GUARD_SETTINGS { get; set; }
        public DbSet<WL_LIST_ISSUES> WL_LIST_ISSUES { get; set; }
    }
}
