//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_CHECK_DATES
    {
        public int INC_ID { get; set; }
        public Nullable<System.DateTime> next_check { get; set; }
        public Nullable<System.DateTime> last_check { get; set; }
    }
}
