//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_LIST_GUARD_SETTINGS
    {
        public int Inc_ID { get; set; }
        public int Lookback { get; set; }
        public int Frequency { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public string AutoPull { get; set; }
        public string REACT { get; set; }
        public string AutomatedandFull { get; set; }
    }
}
