//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WL_LIST_GUARD
    {
        public int Encrypted_Email_ID { get; set; }
        public int Inc_ID { get; set; }
        public System.DateTime StoS_Added { get; set; }
        public System.DateTime StoS_Last { get; set; }
        public string StoS_Source { get; set; }
        public string StoS_Job_ID { get; set; }
        public Nullable<System.DateTime> WL_Last_Check { get; set; }
        public Nullable<System.DateTime> WL_Next_Check { get; set; }
        public string WL_Last_Finding { get; set; }
        public string WL_Last_Comment { get; set; }
        public Nullable<int> Issue_ID { get; set; }
        public int WL_LG_ID { get; set; }
    }
}
